### ISSUE TITLE
[Epic] update Core Contracts

### ISSUE THREAD

**Issue by jorgemmsilva** [iotaledger/wasp#114]
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/isc-private/issues/142
- [ ] https://github.com/iotaledger/isc-private/issues/143
- [ ] https://github.com/iotaledger/isc-private/issues/144
- [x] https://github.com/iotaledger/isc-private/issues/145
- [x] https://github.com/iotaledger/isc-private/issues/146
```
