### ISSUE TITLE
[Epic] update VM

### ISSUE THREAD

**Issue by jorgemmsilva** [iotaledger/wasp#115]
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/isc-private/issues/138
- [ ] https://github.com/iotaledger/isc-private/issues/139
- [ ] https://github.com/iotaledger/isc-private/issues/140
- [ ] https://github.com/iotaledger/isc-private/issues/141
```
