### ISSUE TITLE
[Epic] Update consensus

### ISSUE THREAD

**Issue by jorgemmsilva** [iotaledger/wasp#116]
- update code to use the new ISC types
- define interface for nodeconn
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/isc-private/issues/266
- [ ] https://github.com/iotaledger/isc-private/issues/267
- [ ] https://github.com/iotaledger/isc-private/issues/268
```
