### ISSUE TITLE
[Epic] Update WebAPI

### ISSUE THREAD

**Issue by jorgemmsilva** [iotaledger/wasp#127]
The WebAPI still relies heavily on old Stardust behavior. Mostly, it's just mapping that needs to be updated. But it also relies on the old Core Contract Calling Convention which needs to be replaced from isc.Dict to isc.CallArguments.

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/isc-private/issues/312
- [ ] https://github.com/iotaledger/isc-private/issues/313
- [ ] https://github.com/iotaledger/isc-private/issues/314
```

/edit: 28. Oct:
As of now, the wasp-cli is almost compilable but requires some additional changes in the WebAPI before we can finalize this epic. This is primarily the Request field that is missing from the Receipt responses
