### ISSUE TITLE
Serialization overhaul

### ISSUE THREAD

**Issue by jorgemmsilva** [iotaledger/wasp#194]
investigate how to use a standard, reusable framework (like BCS)
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/isc-private/issues/195
- [ ] https://github.com/iotaledger/isc-private/issues/196
- [ ] https://github.com/iotaledger/isc-private/issues/197
- [ ] https://github.com/iotaledger/isc-private/issues/198
- [ ] https://github.com/iotaledger/isc-private/issues/256
```

**Comment by lmoe** [comment]
🥳
