### ISSUE TITLE
Turn `contracts/inccounter` into Core Contract

### ISSUE THREAD

**Issue by lmoe** [iotaledger/wasp#234]
Right now we use the `inccounter` Contract in various tests (This includes spamming, testing contract invocation and other things.) 
This is a standalone contract that needs to be deployed first in Solo/Cluster tests.

As we remove the `blob` contract and contract deployment functionalities that the `inccounter` relies on, we need to turn it into a Core Contract and register it inside the `root` Core Contract, *but only* in a test environment. It should not be loaded when ISC runs in production.

It already contains the rough structure of a core contract, so it's mostly moving files and a little restructure of the code. Maybe use the `errors` Core Contract as a reference and compare what to change.

```[tasklist]
### Tasks
- [x] Turn `inccounter`into a proper Core Contract and register it in test environments
- [x] Refactor all tests using the `inccounter` to the new structure
- [x] Investigate other tests calling (non-EVM) `DeployContract` and refactor if possible.
```

**Comment by vitaliy-io** [comment]
> As we remove the blob contract and contract deployment functionalities that the inccounter relies on, we need to turn it into a Core Contract and register it inside the root Core Contract, but only in a test environment. It should not be loaded when ISC runs in production.


It was discussed that for now we're going to deploy inccounter on every env, will fix that later when we agree on approach to determine `test` environments

**Comment by lmoe** [comment]
Remark: Its not yet checking of Test Environments and is currently always registered.
