### ISSUE TITLE
Fix remaining compilation issues

### ISSUE THREAD

**Issue by lmoe** [iotaledger/wasp#269]
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/isc-private/issues/270
- [ ] https://github.com/iotaledger/isc-private/issues/271
- [ ] https://github.com/iotaledger/isc-private/issues/272
- [ ] https://github.com/iotaledger/isc-private/issues/310
```
