### ISSUE TITLE
[Epic] Fix tests

### ISSUE THREAD

**Issue by lmoe** [iotaledger/wasp#289]
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/isc-private/issues/290
- [ ] https://github.com/iotaledger/isc-private/issues/291
- [ ] https://github.com/iotaledger/isc-private/issues/293
- [ ] https://github.com/iotaledger/isc-private/issues/295
- [ ] https://github.com/iotaledger/isc-private/issues/357
```
